"""
5_About.py – About page for NetSage AI.
"""

import sys
from pathlib import Path
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

import streamlit as st

st.set_page_config(
    page_title="About – NetSage AI",
    page_icon="ℹ️",
    layout="wide",
)

# Master CSS import
from app import GLOBAL_CSS
st.markdown(GLOBAL_CSS, unsafe_allow_html=True)

with st.sidebar:
    st.markdown(
        """
        <div style="padding:10px 4px 16px; text-align:center;">
            <div style="font-size:2.2rem; margin-bottom:4px;">🌐</div>
            <div style="font-family:'Outfit',sans-serif; font-size:1.3rem; font-weight:800; background:linear-gradient(135deg, #38BDF8, #818CF8); -webkit-background-clip:text; -webkit-text-fill-color:transparent;">
                NetSage AI
            </div>
            <div style="font-size:0.75rem; color:#6B7280; font-weight:500; margin-top:2px;">
                System Architecture Docs
            </div>
        </div>
        """,
        unsafe_allow_html=True,
    )
    st.markdown("---")
    st.page_link("app.py", label="🏠 Command Center", use_container_width=True)
    st.page_link("pages/1_AI_Diagnosis.py", label="🔍 AI Diagnosis", use_container_width=True)
    st.page_link("pages/2_Human_Review.py", label="👤 Human Review Board", use_container_width=True)
    st.page_link("pages/3_Dashboard.py", label="📊 Analytics & Metrics", use_container_width=True)
    st.page_link("pages/4_Dataset_Manager.py", label="📁 Dataset Operations", use_container_width=True)
    st.page_link("pages/5_About.py", label="ℹ️ Architecture & Specs", use_container_width=True)

st.markdown(
    '<h1 style="color:#58A6FF;font-weight:800;font-size:2.2rem">ℹ️ About NetSage AI</h1>',
    unsafe_allow_html=True,
)

# Overview
st.markdown(
    """
    <div class="netsage-card">
        <h3 style="color:#58A6FF;margin-top:0">Project Overview</h3>
        <p style="color:#C9D1D9;line-height:1.8">
            <strong>NetSage AI</strong> is a production-quality AI web application that helps junior network engineers
            troubleshoot Cisco Packet Tracer networking labs. It combines a deterministic <strong>rule-based checker</strong>
            with <strong>Google Gemini LLM</strong> to provide structured, evidence-grounded diagnoses across all OSI layers.
        </p>
        <p style="color:#C9D1D9;line-height:1.8">
            The core design principle is <strong>Human-in-the-Loop AI</strong>: every diagnosis generated by the AI
            must be reviewed, and optionally corrected, by a human engineer before it is accepted. This ensures
            responsible deployment and continuous improvement of AI accuracy.
        </p>
    </div>
    """,
    unsafe_allow_html=True,
)

# Architecture
st.markdown("### 🏗️ Architecture")

col1, col2 = st.columns(2)
with col1:
    st.markdown(
        """
        <div class="netsage-card">
            <h4 style="color:#10B981;margin-top:0">🎨 Frontend</h4>
            <ul style="color:#C9D1D9;line-height:2">
                <li>Streamlit 1.35+ multi-page app</li>
                <li>Custom CSS dark theme</li>
                <li>Plotly interactive charts</li>
                <li>Responsive card-based layout</li>
                <li>Inter + JetBrains Mono fonts</li>
            </ul>
        </div>
        """,
        unsafe_allow_html=True,
    )

with col2:
    st.markdown(
        """
        <div class="netsage-card">
            <h4 style="color:#A78BFA;margin-top:0">⚙️ Backend</h4>
            <ul style="color:#C9D1D9;line-height:2">
                <li>Python 3.12+ with type hints</li>
                <li>Google Gemini 1.5 Flash LLM</li>
                <li>Pydantic v2 response validation</li>
                <li>14 deterministic rule checks</li>
                <li>JSON-based logging system</li>
                <li>CSV-based persistence (no DB)</li>
            </ul>
        </div>
        """,
        unsafe_allow_html=True,
    )

# Module map
st.markdown("### 📦 Module Map")
st.markdown(
    """
    <div class="netsage-card">
        <table style="width:100%;border-collapse:collapse;color:#C9D1D9">
            <thead>
                <tr style="border-bottom:1px solid #30363D">
                    <th style="text-align:left;padding:8px 12px;color:#8B949E">Module</th>
                    <th style="text-align:left;padding:8px 12px;color:#8B949E">Responsibility</th>
                </tr>
            </thead>
            <tbody>
                <tr style="border-bottom:1px solid #21262D">
                    <td style="padding:8px 12px;font-family:monospace;color:#60A5FA">modules/ai_engine.py</td>
                    <td style="padding:8px 12px">Gemini API calls, JSON extraction, Pydantic validation, retry logic</td>
                </tr>
                <tr style="border-bottom:1px solid #21262D">
                    <td style="padding:8px 12px;font-family:monospace;color:#60A5FA">modules/rule_checker.py</td>
                    <td style="padding:8px 12px">14 regex/keyword rules for common Cisco faults</td>
                </tr>
                <tr style="border-bottom:1px solid #21262D">
                    <td style="padding:8px 12px;font-family:monospace;color:#60A5FA">modules/diagnosis.py</td>
                    <td style="padding:8px 12px">Orchestrates rule checker + AI + result packaging</td>
                </tr>
                <tr style="border-bottom:1px solid #21262D">
                    <td style="padding:8px 12px;font-family:monospace;color:#60A5FA">modules/csv_manager.py</td>
                    <td style="padding:8px 12px">CRUD for cases.csv and human_review_log.csv</td>
                </tr>
                <tr style="border-bottom:1px solid #21262D">
                    <td style="padding:8px 12px;font-family:monospace;color:#60A5FA">modules/dashboard.py</td>
                    <td style="padding:8px 12px">8 Plotly chart builders with dark theme</td>
                </tr>
                <tr style="border-bottom:1px solid #21262D">
                    <td style="padding:8px 12px;font-family:monospace;color:#60A5FA">modules/prompt_loader.py</td>
                    <td style="padding:8px 12px">Loads .md prompt files, assembles user message</td>
                </tr>
                <tr style="border-bottom:1px solid #21262D">
                    <td style="padding:8px 12px;font-family:monospace;color:#60A5FA">modules/logger.py</td>
                    <td style="padding:8px 12px">JSON logging for all events (AI, rules, reviews)</td>
                </tr>
                <tr>
                    <td style="padding:8px 12px;font-family:monospace;color:#60A5FA">modules/utils.py</td>
                    <td style="padding:8px 12px">Shared helpers: formatting, validation, OSI layer utils</td>
                </tr>
            </tbody>
        </table>
    </div>
    """,
    unsafe_allow_html=True,
)

# Tech stack badges
st.markdown("### 🛠️ Technology Stack")
st.markdown(
    """
    <div class="netsage-card">
        <span class="badge badge-blue">🐍 Python 3.12+</span>
        <span class="badge badge-purple">⚡ Streamlit 1.35+</span>
        <span class="badge badge-green">🤖 Google Gemini 1.5 Flash</span>
        <span class="badge badge-blue">📊 Plotly 5.x</span>
        <span class="badge badge-purple">🔒 Pydantic v2</span>
        <span class="badge badge-green">🐼 pandas 2.x</span>
        <span class="badge badge-blue">📁 CSV (no database)</span>
        <span class="badge badge-purple">🗂️ JSON logging</span>
    </div>
    """,
    unsafe_allow_html=True,
)

# How to use
st.markdown("### 🚀 Quick Start")
st.code(
    """# 1. Clone / open the project
cd NetSage-AI

# 2. Create a virtual environment
python -m venv .venv
.venv\\Scripts\\activate      # Windows
# source .venv/bin/activate  # macOS/Linux

# 3. Install dependencies
pip install -r requirements.txt

# 4. Set your Gemini API key
copy .env.example .env
# Edit .env and set GEMINI_API_KEY=your_key_here

# 5. Run the app
streamlit run app.py
""",
    language="bash",
)

# Responsible AI
st.markdown("### 🛡️ Responsible AI Principles")
st.markdown(
    """
    <div class="netsage-card">
        <div style="display:grid;grid-template-columns:1fr 1fr;gap:16px">
            <div>
                <div style="color:#10B981;font-weight:700;margin-bottom:6px">✅ Human-in-the-Loop</div>
                <div style="color:#8B949E;font-size:0.88rem">Every AI output requires human review before use</div>
            </div>
            <div>
                <div style="color:#60A5FA;font-weight:700;margin-bottom:6px">📎 Evidence-Grounded</div>
                <div style="color:#8B949E;font-size:0.88rem">AI only uses provided show output – no hallucination</div>
            </div>
            <div>
                <div style="color:#A78BFA;font-weight:700;margin-bottom:6px">📊 Confidence Scoring</div>
                <div style="color:#8B949E;font-size:0.88rem">Every diagnosis includes a 0-100 confidence score</div>
            </div>
            <div>
                <div style="color:#F59E0B;font-weight:700;margin-bottom:6px">📜 Full Audit Trail</div>
                <div style="color:#8B949E;font-size:0.88rem">All AI calls, reviews, and corrections are logged</div>
            </div>
            <div>
                <div style="color:#EF4444;font-weight:700;margin-bottom:6px">🔄 Correction Tracking</div>
                <div style="color:#8B949E;font-size:0.88rem">Edited diagnoses are saved and displayed for learning</div>
            </div>
            <div>
                <div style="color:#34D399;font-weight:700;margin-bottom:6px">🔐 Rule-First</div>
                <div style="color:#8B949E;font-size:0.88rem">Deterministic rules run before AI for fast detection</div>
            </div>
        </div>
    </div>
    """,
    unsafe_allow_html=True,
)

st.markdown(
    '<div style="text-align:center;color:#6B7280;font-size:0.8rem;margin-top:40px">'
    'NetSage AI v1.0.0 · Built for educational and demonstration purposes · '
    'Powered by Google Gemini &amp; Streamlit'
    '</div>',
    unsafe_allow_html=True,
)
